// This is an autogenerated file from Firebase Studio.

'use server';

/**
 * @fileOverview Generates a potential travel itinerary based on a selected travel deal.
 *
 * - generateTravelItinerary - A function that generates a travel itinerary.
 * - GenerateTravelItineraryInput - The input type for the generateTravelItinerary function.
 * - GenerateTravelItineraryOutput - The return type for the generateTravelItinerary function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const GenerateTravelItineraryInputSchema = z.object({
  dealDescription: z
    .string()
    .describe('A description of the travel deal, including destination, dates, and price.'),
  interests: z
    .string()
    .describe('The users interests for the trip, example: beach vacation, adventure, relaxation.'),
  budget: z.number().describe('The budget for the trip in USD.'),
  departureCity: z.string().describe('The city the user will be departing from.'),
});
export type GenerateTravelItineraryInput = z.infer<
  typeof GenerateTravelItineraryInputSchema
>;

const GenerateTravelItineraryOutputSchema = z.object({
  itinerary: z.string().describe('A detailed travel itinerary based on the deal.'),
});
export type GenerateTravelItineraryOutput = z.infer<
  typeof GenerateTravelItineraryOutputSchema
>;

export async function generateTravelItinerary(
  input: GenerateTravelItineraryInput
): Promise<GenerateTravelItineraryOutput> {
  return generateTravelItineraryFlow(input);
}

const prompt = ai.definePrompt({
  name: 'generateTravelItineraryPrompt',
  input: {schema: GenerateTravelItineraryInputSchema},
  output: {schema: GenerateTravelItineraryOutputSchema},
  prompt: `You are a travel expert specializing in creating detailed travel itineraries.

  Based on the following travel deal and the user's interests and budget, create a detailed day-by-day travel itinerary. The itinerary should include specific activities, estimated costs, and considerations for maximizing the experience within the given budget.

  Travel Deal Description: {{{dealDescription}}}
  User Interests: {{{interests}}}
  Budget: ${{{budget}}} USD
  Departure City: {{{departureCity}}}

  Focus on creating a realistic and engaging itinerary that aligns with the user's preferences.
  The itinerary must not be more than 7 days long.
  `,
});

const generateTravelItineraryFlow = ai.defineFlow(
  {
    name: 'generateTravelItineraryFlow',
    inputSchema: GenerateTravelItineraryInputSchema,
    outputSchema: GenerateTravelItineraryOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
